//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesOptimizer
{
    using System;
    using System.Collections.Generic;
    
    public partial class services
    {
        public decimal ServiceId { get; set; }
        public string MsName { get; set; }
        public string MsCaption { get; set; }
        public string MsState { get; set; }
        public string MsStartMode { get; set; }
        public string MsSuggestion { get; set; }
        public string MsNoNetwork { get; set; }
        public string MsDesc { get; set; }
        public string MsPath { get; set; }
        public Nullable<bool> MsIsChecked { get; set; }
        public string ColorSet { get; set; }
        public string FontWeightSet { get; set; }
        public string MsGroupe { get; set; }
        public string MsAction { get; set; }
        public string MsToolTip { get; set; }
        public string MsInfo { get; set; }
    }
}
